apiVersion: v1
kind: Service
metadata:
  name: {{ include "habit-tracker.fullname" . }}-backend
  labels:
    {{- include "habit-tracker.backend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: habit-tracker-backend
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.port }}
