apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "habit-tracker.fullname" . }}-config
  labels:
    {{- include "habit-tracker.labels" . | nindent 4 }}
    component: config
data:
  NEXT_PUBLIC_API_URL: {{ .Values.config.backendUrl | quote }}
