apiVersion: v1
kind: Service
metadata:
  name: {{ include "habit-tracker.fullname" . }}-frontend
  labels:
    {{- include "habit-tracker.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: habit-tracker-frontend
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.port }}
    {{- if eq .Values.frontend.service.type "NodePort" }}
    nodePort: {{ .Values.frontend.service.nodePort }}
    {{- end }}
