apiVersion: v1
kind: Service
metadata:
  name: habit-tracker-backend
  labels:
    app: habit-tracker-backend
    component: backend
spec:
  type: ClusterIP
  selector:
    app: habit-tracker-backend
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000
