apiVersion: v1
kind: Service
metadata:
  name: habit-tracker-frontend
  labels:
    app: habit-tracker-frontend
    component: frontend
spec:
  type: NodePort
  selector:
    app: habit-tracker-frontend
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30080
